### ISSUE TITLE
1.0.4: tests/ directory not included in pypi sdist tar ball

### ISSUE THREAD

**Issue by kloczek** [hukkin/tomli#100]
Yeah .. looks like test suite is not included :/

**Comment by hukkin** [comment]
Hey, thanks for the issue!

Tests are excluded on purpose. My understanding is that distributing tests in sdist is not best practice and I know that e.g. some [PyPA folks](https://github.com/executablebooks/sphinx-tabs/issues/97#issuecomment-826134549) think the same.

There is a git tag corresponding each release, and tests are available on git.

**Comment by kloczek** [comment]
What you mean "distributing tests in sdist is not best practice"?
So how can I perform tests??
PyPA folks does not work on OS distribution and they don't know that test suite is not only about testing module in which test suite is included but testing as well whole set of packages installed in build env. More test units than higher chance that some error in tested module or env will be found.

Thx to share that link. I just added comment under that ticket.

**Comment by hukkin** [comment]
> What you mean "distributing tests in sdist is not best practice"?

This should be explained in the link I posted.

> So how can I perform tests??

By using git instead of PyPI.

I noticed you started discussion in the linked issue so I'll be following that and may adjust my views based on arguments made there.
