### ISSUE TITLE
Valid when creating a dotted key with the path of a previously created table

### ISSUE THREAD

**Issue by python36** [hukkin/tomli#123]
Please take a look at the discussion
https://github.com/marzer/tomlplusplus/issues/113

**Comment by hukkin** [comment]
Thanks for the issue!

It doesn't seem clear to me that Tomli is in the wrong here. Could you provide a TOML snippet to reproduce and quote/link the part of the TOML v1.0.0 spec that makes you think it is parsed incorrectly?

**Comment by python36** [comment]
I think Tomli is working correctly. I just wanted to hear your opinion on this difficult issue.

**Comment by hukkin** [comment]
Ah great :+1: I wrote out my thoughts in the linked tomlplusplus issue and will follow the discussion there. Currently I also think Tomli is in the right so closing this. Let's reopen if we later come to another conclusion.

Thanks for involving me!
