### ISSUE TITLE
Include setup.py in sdist

### ISSUE THREAD

**Issue by jameshilliard** [hukkin/tomli#144]
I noticed `setup.py` was [removed here](https://github.com/hukkin/tomli/commit/026f249c1dfaf95e6839977d98a555e057f5c2ba), however since `tomli` is a required dependency for bootstrapping `flit` this should be included to make installing `flit` easier for distros that need it for setting up a PEP-517 build environment.

**Comment by hukkin** [comment]
This has been discussed before. Please see https://github.com/hukkin/tomli/issues/122#issuecomment-907822085

For bootstrapping see https://github.com/FFY00/python-bootstrap and https://flit.readthedocs.io/en/latest/bootstrap.html

**Comment by jameshilliard** [comment]
> For bootstrapping see https://github.com/FFY00/python-bootstrap and https://flit.readthedocs.io/en/latest/bootstrap.html

Best I can tell nothing here actually covers installing `tomli` for distro build systems that don't already have wheel support(for various reasons we don't support wheels in [buildroot](https://buildroot.org/) at the moment, only sdists with `setup.py`).

I don't see any downside to including a `setup.py` for those that need it for bootstrapping, at least until the tooling situation improves a bit more(pep-517 tooling is still pretty bad for complex cross compilation scenarios in [buildroot](https://buildroot.org/) from what I can tell).

For now I'm having to use a version from before `setup.py` was removed since it's creating a recursive dependency issue for bootstrapping `flit`.

**Comment by hukkin** [comment]
I really don't have much to add to https://github.com/hukkin/tomli/issues/122#issuecomment-907822085 and it even suggests a couple ways to solve your problem. Also note that there's like [40 distros/projects](https://repology.org/project/python:tomli/versions) successfully repackaging Tomli already. Maybe you can learn from their processes.

I have no interest in maintaining a `setup.py` in this project. If you do then please make a fork, the license is MIT, you're welcome!

**Comment by jameshilliard** [comment]
> I have no interest in maintaining a `setup.py` in this project.

You should probably remove this comment then:
> If you're a packager and absolutely need this file, please create an issue.

**Comment by hukkin** [comment]
> Still not sure how one flag for flit is a maintenance burden at all.

It isn't except when Python 3.12 is released and the setup.py stops working. Please read https://github.com/hukkin/tomli/issues/122#issuecomment-907822085. Also I don't currently use `flit` as build frontend, I use `build` so I'd need to change that.

> You should probably remove this comment then:

Yeah maybe I should. The thing is I'm not very convinced you have an _absolute_ need for this file. Why can't you add a one-liner setup.py yourself for building? Why can't you have wheel support? Are you sure you even need to build a package that is pure Python?

**Comment by jameshilliard** [comment]
> It isn't except when Python 3.12 is released and the setup.py stops working.

Hopefully by then the tooling will have matured more, but it would be nice if the migration path wasn't so horribly complex, python cross compilation is a huge hacky mess and difficult to maintain as is.

Isn't python 3.12 something like 2 years away from being released anyways? I mean python 3.11(last version compatible with distutils) isn't even going to be EOL until 2027 looks like....so seems a bit premature removing `setup.py` when that is the case.

> The thing is I'm not very convinced you have an absolute need for this file. Why can't you add a one-liner setup.py yourself for building?

Obviously I can make some ugly unmaintainable temporary hack if I have to, but that sort of thing tends to cause issues whenever we make changes to our tooling.

> Why can't you have wheel support? Are you sure you even need to build a package that is pure Python?

We cross compile all packages so there wasn't much point since wheels are inherently incompatible with cross compilation for packages with c extensions...and we really don't want to special case pure-python packages for complexity reasons.

**Comment by jameshilliard** [comment]
So rather than include a `setup.py` maybe `tomli` should be fixed so that it complies with the [PEP-517 Build Requirements](154).
