### ISSUE TITLE
Alias for TOMLDecodeError → TomlDecodeError

### ISSUE THREAD

**Issue by frenzymadness** [hukkin/tomli#167]
Hello.

We are writing tool called micropipenv (https://github.com/thoth-station/micropipenv) and we are trying to make it compatible with various toml backends.

Would it make sense to create an alias for TOMLDecodeError - TomlDecodeError to make it the same as it is in this implementation: https://github.com/uiri/toml/blob/3f637dba5f68db63d4b30967fedda51c82459471/toml/__init__.py#L15 ?

After that, it'd be possible to import toml/tomli and use the same exception name no matter what implementation is available.

What do you think about it?

**Comment by hukkin** [comment]
Hey thanks for the issue!

Please read https://github.com/hukkin/tomli/pull/88
