### ISSUE TITLE
TOMLDecodeError: Invalid initial character for a key part

### ISSUE THREAD

**Issue by marxin** [hukkin/tomli#199]
I noticed `tomli` is stricter than [`toml`](https://github.com/uiri/toml) when it comes to whitespaces:

```
$ cat sample.toml
digests = [
  {
    key = "value",
    key2 = "value2"
  }
]
$ In [4]: toml.load('sample.toml')
Out[4]: {'digests': [{'key': 'value', 'key2': 'value2'}]}
$ In [5]: tomli.load(open('sample.toml', 'rb'))
...
    403     return parse_one_line_basic_str(src, pos)
--> 404 raise suffixed_err(src, pos, "Invalid initial character for a key part")

TOMLDecodeError: Invalid initial character for a key part (at line 2, column 4)
```
Is it something that can be relaxed, please?

**Comment by hukkin** [comment]
Hi there!

Tomli implements the TOML spec. This can only be relaxed if the spec changes. Quoting https://toml.io/en/v1.0.0#inline-table
> No newlines are allowed between the curly braces unless they are valid within a value.

I'm closing this in favor of https://github.com/toml-lang/toml/issues/516

**Comment by marxin** [comment]
Thanks, appreciate your fast reply.

**Comment by jakirkham** [comment]
Thank you both for your discussion of this issue and raising this with the upstream spec! 🙏

It looks like upstream has resolved the issue: https://github.com/toml-lang/toml/issues/516

In particular they implemented this behavior of multiline tables in the spec with PR: https://github.com/toml-lang/toml/pull/904

Here is [the current text covering multine tables]( https://github.com/toml-lang/toml/blob/41e6bcf6ec4da9527a8fc3914565cdde8411936e/toml.md?plain=1#L840-L842 ) and [an associated example]( https://github.com/toml-lang/toml/blob/41e6bcf6ec4da9527a8fc3914565cdde8411936e/toml.md?plain=1#L848-L857 ). Inlining a succinct version of this text below for simplicity:

> Inline tables can have multiple key/value pairs on the same line, or they can be put on different lines. A terminating comma (also called trailing comma) is permitted after the last key/value pair.
>
> ...
>
> ```toml
> contact = {
>     personal = {
>         name = "Donald Duck",
>         email = "donald@duckburg.com",
>     },
>     work = {
>         name = "Coin cleaner",
>         email = "donald@ScroogeCorp.com",
>     },
> }
> ```

Given the upstream spec has accepted this change, would we be willing to reconsider this change?

Thank you for your help! 🙂
