### ISSUE TITLE
cannot install tomli by pip-compile

### ISSUE THREAD

**Issue by maogongyin** [hukkin/tomli#205]
I used to manage dependency by pip-compile and requirements.in .
But I can not install tomli via pip-compile.
$ pip-compile 
Could not find a version that matches tomli (from -r requirements.in (line 4))
No versions found
Was https://pypi.org/simple reachable?
$ python3
Python 3.9.6 (default, Aug 15 2021, 21:24:28) `

**Comment by hukkin** [comment]
Hello there!

This doesn't seem like a Tomli issue. Could you try filing an issue on https://github.com/jazzband/pip-tools/issues ?
