### ISSUE TITLE
On Windows only: TOML parsing error: "Couldn't read config file pyproject.toml: Unescaped '\' in a string"

### ISSUE THREAD

**Issue by AndydeCleyre** [hukkin/tomli#210]
I wrote out the details at nedbat/coveragepy#1481, as the problem was encountered during use of coveragepy in a Windows CI run. I don't have a local Windows environment handy to test with.

The meat of it is, I have this entry in a TOML file, and I think it's valid, and it parses fine on Linux and MacOS, but not Windows, using tomli 2.0.1:

```toml
install = "if [ $VIRTUAL_ENV ]; then pip install -r local-requirements.txt; else printf '%s\n' 'Please activate a venv first'; return 1; fi"
```

Result on Windows:

```
Couldn't read config file pyproject.toml: Unescaped '\' in a string (at line 62, column 21)
```

**Comment by hauntsaninja** [comment]
I unfortunately don't have a Windows machine at hand, so can't repro. One thing that would help is if you could test whether you get a failure when using tomli directly. I suspect this is related to the weird substitution stuff that coverage seems to be doing: https://github.com/nedbat/coveragepy/blob/57d86492daeca737ce4dfaff648d00dfe070b965/coverage/tomlconfig.py#L55

That is, do things fail with:
```
import tomli

with open("pyproject.toml", "rb") as f:
    tomli.load(f)

with open("pyproject.toml", "r", encoding="utf-8") as f:
    tomli.loads(f.read())
```

**Comment by AndydeCleyre** [comment]
Thanks! I added your repro snippet as a nox session running with Python 3.10, and it ran successfully even on Windows.
