### ISSUE TITLE
MicroPython Support

### ISSUE THREAD

**Issue by BrianPugh** [hukkin/tomli#218]
I've made a fork of tomli that supports micropython:

https://github.com/BrianPugh/micropython-tomli

A lot of the changes make the codebase worse from a cpython perspective (removed type hints, uglier regex, etc etc), so I'm not looking to make a PR or anything. I was wondering if you'd be interested in linking my fork from your readme? If you think micropython may be too niche, I also understand not wanting to clutter the readme.

Thanks!

**Comment by encukou** [comment]
Since `tomli` is part of Python's standard library (as `tomllib`), you might instead want to get your fork included in https://github.com/micropython/micropython-lib, to better integrate with the MicroPython ecosystem.
Not sure if tomli's README is the place people look at for this kind of info.
