### ISSUE TITLE
Parsing Backslashes Duplicates Them

### ISSUE THREAD

**Issue by ArsThaumaturgis** [hukkin/tomli#228]
For my current project, I'm attempting to decode some TOML text that contains backslashes--those being present for the purposes of passing them to another module that incorporates them in its markup.

Unfortunately, it seems that whenever they're found, the TOML interpreter duplicates them--thus breaking the markup.

Here below is a short program that, on my machine at least, demonstrates the issue:
```python
import tomli

mew = "cat = 'this is a \ test'"
result = tomli.loads(mew)
print (result)
```
Which on my machine produces the following output:
```{'cat': 'this is a \\ test'}```

(And the same output seems to be produced if I escape the backslash.)

[edit]
A little more experimentation has turned up much the same with other approaches at handling the string: whether using basic or literal strings, or whether sourced from a Python string or loaded from a file, I thus far have found no way of getting just a single backslash to appear alone...

**Comment by hukkin** [comment]
Hi!

This behavior has nothing to do with Tomli really. If you print out a `dict` there will be escape sequences for some characters, see https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences

A double backslash is the escape sequence of a single backslash.

**Comment by ArsThaumaturgis** [comment]
Hmm... You're right--and even the debugger in PyCharm is printing that way, to my annoyance. (Confirmed by printing each character one at a time, which showed only a single backslash.)

Something else must be going wrong that the markup is being broken, then. (Said markup works with a basic string not derived from TOML, and doesn't with a similar basic string derived from TOML. Which, to be clear, doesn't mean that the problem lies on the TOML side--there are a few moving parts involved in the system that's using it.)

I'll investigate further then, I intend!

Thank you for your time!

**Comment by rdb** [comment]
I'm still a little confused by the tomli behaviour here. According to the tomli 0.4.0 spec:

> All other escape sequences not listed above are reserved and, if used, TOML should produce an error.

It sounds to me like this says that `tomli` should be producing an error when encountering `\ ` (certainly when not at the end of a line). It is instead silently ignoring the sequence. Is that a bug, or have I misread the spec?

**Comment by hukkin** [comment]
That's not a bug. The part of spec you refer to describes basic strings, but a literal string was used in ArsThaumaturgis's TOML.
