### ISSUE TITLE
Looking to help

### ISSUE THREAD

**Issue by snapperVibes** [hukkin/tomli#76]
Tomli seems really well put together. I want to make sure it gets maintained. Let me know if there's anything I can do 🙂

**Comment by hukkin** [comment]
> Tomli seems really well put together

Thanks for the kind words!

> Let me know if there's anything I can do

The project is in a good state where I think there shouldn't be too much to do anymore. Maybe you're able to spot something that could be improved that I don't, however? The [writer module](https://github.com/hukkin/tomli-w) is just a few days old and most certainly isn't perfect yet.

Closing this as I can't think of anything concrete right now, but PRs and issues are welcome if you can think of something!
